### ISSUE TITLE
"type mismatch" in com.ibm.wala.escape.FILiveObjectAnalysis

### ISSUE THREAD

**Issue by mamarsh** [wala/WALA#151]
We've been using a fork of WALA, and with the new release I was hoping to move us back to the mainline.  I'm getting an error when compiling, though:

```
[error] /a/file/path/MyFile.scala:27: type mismatch;
[error]  found   : com.ibm.wala.analysis.pointers.HeapGraph[_$1] where type _$1 <: com.ibm.wala.ipa.callgraph.propagation.InstanceKey
[error]  required: com.ibm.wala.analysis.pointers.HeapGraph[com.ibm.wala.ipa.callgraph.propagation.InstanceKey]
[error] Note: _$1 <: com.ibm.wala.ipa.callgraph.propagation.InstanceKey, but Java-defined trait HeapGraph is invariant in type T.
[error] You may wish to investigate a wildcard type such as `_ <: com.ibm.wala.ipa.callgraph.propagation.InstanceKey`. (SLS 3.2.10)
[error]     val liveAnalysis = new FILiveObjectAnalysis(GlobalHeap.cg, GlobalHeap.heap, false)
```

It might be worth checking all of the changes from commit fde65340d22f153914343a33bbaf6f5497ce67f4 (where this was introduced) for similar issues.

**Comment by msridhar** [comment]
@liblit can you take a look?

**Comment by msridhar** [comment]
@mamarsh do you have a pure Java example to reproduce?

**Comment by mamarsh** [comment]
@msridhar I don't, unfortunately.  I can try to put one together, but I'm not sure how long that'll take me.

**Comment by msridhar** [comment]
@mamarsh ok, if you have time to actually explain the problem here, that'd be helpful 😄 I'm not an expert in Scala compile warnings.

**Comment by liblit** [comment]
@mamarsh, thank you for tracking this down to a specific commit, which turns out to have come from me. I am sorry for the disruption those changes are causing you.

Like @msridhar, I am no Scala expert. Doing my best to decode the error message and infer what might be happening, here is what I see. Scala is finding a value (in your code) whose static type is what Java would call `HeapGraph<? super InstanceKey>`. However, what it was actually expecting was `HeapGraph<InstanceKey>`. So that's a static type mismatch. Apparently the code that leads to this error is the following Scala fragment:

``` scala
val liveAnalysis = new FILiveObjectAnalysis(GlobalHeap.cg, GlobalHeap.heap, false)
```

Although I cannot see the surrounding context, based on the names I would guess that `GlobalHeap.heap` is the offending value. @mamarsh, what is the type of this item? My guess is that it has type `HeapGraph<? super InstanceKey>` (or whatever the syntax for that is in Scala). Looking at `FILiveObjectAnalysis`, I see that its constructor does expect `HeapGraph<InstanceKey>`, so that would be a type mismatch.

Looking back at my commit that causes this type error to appear, I see that I did indeed [change the type of this constructor argument](https://github.com/wala/WALA/commit/fde65340d22f153914343a33bbaf6f5497ce67f4#diff-6f505606d6841bf44858283ce76371ceL71). Previously it accepted any `HeapGraph`, without regard for the generic type parameter. My change makes it more picky: it requires specifically a `HeapGraph<InstanceKey>`. So there's more static checking going on now than there was before.

How do we fix this? The first thing I'd request is that you look into the type for that `GlobalHeap.heap` value. Can you change it to be `HeapGraph<InstanceKey>` instead of `HeapGraph<? super InstanceKey>`? If so, just do that and all should be well. If there is some reason why this cannot be fixed on your end, then I suppose we can explore what it would take to relax the type expected by the `FILiveObjectAnalysis` constructor. That might be just a minor, local thing. Or it might cause propagating changes that affect many more things too. I am happy to look into this, but first let's see whether the problem is easy to fix on your side by changing the type of `GlobalHeap.heap` to `HeapGraph<InstanceKey>`.

**Note 1:** I have used Java type syntax throughout, because I don't know Scala well at all. @mamarsh, I hope you'll be able to convert without too much difficulty.

**Note 2:** For the sake of readability, I have abbreviated `com.ibm.wala.analysis.pointers.HeapGraph` as `HeapGraph`, and I have abbreviated `com.ibm.wala.ipa.callgraph.propagation.InstanceKey` as `InstanceKey`.

**Comment by mamarsh** [comment]
@liblit Yes, what you've written makes sense.  I changed the Scala code to specify `HeapGraph<InstanceKey>` instead of `HeapGraph<?>` (the Scala is a little different), which then compiles.  I don't know if everything works with that, because we're using Illinois's wala-facade, which still has `ClassHierarchy.make()`, so our testing fails.

I've also put together a Java test that I think highlights the equivalent problem:

```
public final class FILiveObjectAnalysisTest extends WalaTestCase {
  
  public static void main(final String[] args) {
    justThisTest(FILiveObjectAnalysisTest.class);
  }
  
  // --- Test cases
  
  @Test public void testCase1() {
    final CallGraph cg = null; //new CallGraph();
    final HeapGraph<ConstantKey> heap = null; //new BasicHeapGraph();
    Assert.assertTrue(issubtype(ConstantKey, InstanceKey));
    final FILiveObjectAnalysis liveAnalysis = new FILiveObjectAnalysis(cg, heap, false);
    Assert.assertNotNull(liveAnalysis);
  }
}
```

**Comment by liblit** [comment]
@mamarsh, thanks for trying that out.

@msridhar, there are two ways we could proceed from here. I checked what it would take to relax the `FILiveObjectAnalysis` constructor to accept any `HeapGraph<? super InstanceKey>` instead of insisting only on `HeapGraph<InstanceKey>`. This turns out to be an easy, small change. We just need to change that argument type and also the type of the corresponding private `FILiveObjectAnalysis.heapGraph` field. So we could make just that change and @mamarsh will be in good shape.

However, @mamarsh suggested a more thorough reexamination:
> It might be worth checking all of the changes from commit fde6534 (where this was introduced) for similar issues.

He has a good point. Before that commit, we had an argument of type `HeapGraph`. This was *under-constrained*, because there are plenty of instantiations of `HeapGraph` that would fail here, such as `HeapGraph<Object>` or `HeapGraph<String>`. After my commit, the argument is constrained to be `HeapGraph<InstanceKey>`. Presumably we like the extra checking here, but this actually turns out to be *over-constrained*, because it excludes `HeapGraph<SomeSubclassOfInstanceKey>`, which would actually work just fine. There's a very good chance that other changes in commit fde6534 had the same effect: taking us from being under-constrained to being over-constrained. While WALA's own regression tests all pass, there is a big world of third-party WALA code out there that we may now be excluding because my change made some types be over-constrained.

Do you think I should attempt a systematic sweep over my own commit fde6534 looking for other, similar cases? Essentially, I'll be hunting for types that were `T` before my change, are now `T<U>` after my change, but could actually be `T<? super U>` instead. Is that worth doing? Or should we content ourselves with fixing just @mamarsh's immediate problem and address any others only when problems are reported?

**Comment by msridhar** [comment]
I think a more systematic sweep is unwarranted.  I'd rather have users come and complain about some over-constraint that is actually affecting their code, rather than spending the significant time required to preemptively fix every possible over-constraint.  Users can stay on the old version of WALA if they really need to.

So if you could just do the local change to address @mamarsh's problem, I think that's enough for now.  Thanks!

**Comment by msridhar** [comment]
@mamarsh I just merged @liblit's fix.  Can you confirm it fixes your problem?

**Comment by mamarsh** [comment]
It still fails with that change, however, the following makes it work:

```
diff --git a/com.ibm.wala.core/src/com/ibm/wala/escape/FILiveObjectAnalysis.java b/com.ibm.wala.core/src/com/ibm/wala/escape/FILiveObjectAnalysis.java
index 16ecd54d7..3a583be6d 100644
--- a/com.ibm.wala.core/src/com/ibm/wala/escape/FILiveObjectAnalysis.java
+++ b/com.ibm.wala.core/src/com/ibm/wala/escape/FILiveObjectAnalysis.java
@@ -48,7 +48,7 @@ public class FILiveObjectAnalysis implements ILiveObjectAnalysis {
   /**
    * Graph view of pointer analysis results
    */
-  private final HeapGraph<? super InstanceKey> heapGraph;
+  private final HeapGraph<? extends InstanceKey> heapGraph;
 
   /**
    * Cached map from InstanceKey -> Set<CGNode>
@@ -68,7 +68,7 @@ public class FILiveObjectAnalysis implements ILiveObjectAnalysis {
   /**
    * 
    */
-  public FILiveObjectAnalysis(CallGraph callGraph, HeapGraph<? super InstanceKey> heapGraph, boolean expensiveIntraproceduralAnalysis) {
+  public FILiveObjectAnalysis(CallGraph callGraph, HeapGraph<? extends InstanceKey> heapGraph, boolean expensiveIntraproceduralAnalysis) {
     super();
     this.callGraph = callGraph;
     this.heapGraph = heapGraph;
```

**Comment by liblit** [comment]
Oops, I had a brain-glitch and inverted `super` versus `extends`. Sorry!

The revised pull request should get this right. (Though @msridhar may want to wait for the Travis results just to be sure.)

**Comment by mamarsh** [comment]
No worries. I appreciate the incredibly fast turn-around!


On Mar 22, 2017 5:21 PM, "Ben Liblit" <notifications@github.com> wrote:

Oops, I had a brain-glitch and inverted super versus extends. Sorry!

The revised pull request should get this right. (Though @msridhar
<https://github.com/msridhar> may want to wait for the Travis results just
to be sure.)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wala/WALA/issues/151#issuecomment-288543769>, or mute
the thread

**Comment by msridhar** [comment]
Ok, #153 is now merged.  @mamarsh can you try again? 😄

**Comment by mamarsh** [comment]
:thumbsup: :smile: Thanks!

**Comment by msridhar** [comment]
Cool.  @mamarsh let me know if it'd be helpful for us to cut a new release now that this is fixed; I'm open to it.

**Comment by mamarsh** [comment]
That would be helpful -- thanks.
