### ISSUE TITLE
Update to compile with Eclipse Luna

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#56]
I'm running Eclipse Kepler SR2 with the patched JDT to handle Java 8, and I get the following compile errors in com.ibm.wala.ide.jdt:

```
Description	Resource	Path	Location	Type
The type FakeExceptionTypeBinding must implement the inherited abstract method ITypeBinding.getTypeAnnotations()	FakeExceptionTypeBinding.java	/com.ibm.wala.ide.jdt/source/com/ibm/wala/cast/java/translator/jdt	line 58	Java Problem
The type FakeExceptionTypeBinding must implement the inherited abstract method ITypeBinding.getFunctionalInterfaceMethod()	FakeExceptionTypeBinding.java	/com.ibm.wala.ide.jdt/source/com/ibm/wala/cast/java/translator/jdt	line 58	Java Problem
```
I'm guessing these errors will persist under Eclipse Luna.  Nothing urgent, just noting for future reference.

**Comment by msridhar** [comment]
This is fixed now

**Comment by denis-bogdanas** [comment]
I still get a similar error with wala 1.3.8:

The type FakeExceptionTypeBinding must implement the inherited abstract method ITypeBinding.getDeclaringMember()

**Comment by liblit** [comment]
@denis-bogdanas, I am seeing the same problem with `ITypeBinding.getDeclaringMember()` under Eclipse Mars. I have reported this as a separate WALA issue: #98.

**Comment by denis-bogdanas** [comment]
As workaround you can add an empty implementation of that method. The other methods in that class don't do much either.
